# Travis CI build pipeline
# --------------------------------------------
language: c
os: linux

addons:
  apt:
    packages:
#      - binutils-avr
#      - avr-libc
#      - gcc-avr
      - git

install:
  - |
    git --version
#    avr-gcc --version
#    make --version
  - |
    wget http://packs.download.atmel.com/Atmel.ATtiny_DFP.2.0.368.atpack
    unzip *.atpack -d ./Firmware/DFP
  - |
    wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-3.7.0.1796-linux.any.x86_64.tar.gz
    tar -xf *.tar.gz

before_script:
  - set -e
  - |
    mkdir TEST
    cd TEST
  - |
    ../avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -x c -O1 -mmcu=atmega16a -std=gnu99 -c ../Firmware/TEST/main.c
    ../avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -x c -O1 -mmcu=atmega16a -std=gnu99 -c ../Firmware/TEST/spi/spi.c
    ../avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -x c -O1 -mmcu=atmega16a -std=gnu99 -c ../Firmware/TEST/matrix/matrix.c
  - |
    cd ..
    mkdir DISPLAY
    cd DISPLAY
    ../avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -x c -O1 -mmcu=attiny406 -std=gnu99 -B ../Firmware/DFP/gcc/dev/attiny406 -I ../Firmware/DFP/include -c ../Firmware/DISPLAY/main.c
    ../avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -x c -O1 -mmcu=attiny406 -std=gnu99 -B ../Firmware/DFP/gcc/dev/attiny406 -I ../Firmware/DFP/include -c ../Firmware/DISPLAY/matrix/matrix.c
  - cd ..

script:
  - |
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -mmcu=atmega16a -o test.elf ./TEST/main.o ./TEST/spi.o ./TEST/matrix.o
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-objcopy -j .text -j .data -O ihex test.elf test.hex
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-objcopy -j .eeprom --change-section-lma .eeprom=0 -O ihex test.elf test.eep
  - |
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc -g -mmcu=attiny406 -B ./Firmware/DFP/gcc/dev/attiny406 -I ./Firmware/DFP/include -o display.elf ./DISPLAY/main.o ./DISPLAY/matrix.o
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-objcopy -j .text -j .data -O ihex display.elf display.hex
    ./avr8-gnu-toolchain-linux_x86_64/bin/avr-objcopy -j .eeprom --change-section-lma .eeprom=0 -O ihex display.elf display.eep

before_deploy:
  - |
    if [ -n $TRAVIS_TAG ] && [[ $TRAVIS_TAG =~ ^v[0-9].[0-9]-[(F|f)]irmware$ ]]; then
      travis_terminate 0
    fi
  - set -e
  - git config --local user.name "0x007E"
  - |
    zip -r ./Display.zip ./display.hex ./display.eep
    tar cfvz ./Display.tar.gz ./display.hex ./display.eep
  - |
    zip -r ./Test.zip ./test.hex ./test.eep
    tar cfvz ./Test.tar.gz ./test.hex ./test.eep
  - export TRAVIS_TAG="${TRAVIS_TAG}-Firmware"

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  name: "Firmware ${TRAVIS_TAG}"
  file_glob: true
  file:
    - "./Display.zip"
    - "./Display.tar.gz"
    - "./Test.zip"
    - "./Test.tar.gz"
  skip_cleanup: true
  on:
    tags: true
