name: matrix

on:
  push:
    paths:
    - './PCB/**.sch'
    - './PCB/**.kicad_pcb'
  pull_request:
    paths:
      - './PCB/**.sch'
      - './PCB/**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v2_k6
      with:
        # Required - kibot config file
        config: './PCB/config.kibot.yaml'
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: './PCB/matrix.kicad_sch'
        # optional - PCB design file
        board: './PCB/matrix.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: './PCB/output'
        
        
